# Generated by Django 6.0.5 on 2026-05-14 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Qurilma nomi')),
                ('avg_power_watts', models.FloatField(verbose_name="O'rtacha quvvati (Vatt)")),
                ('category', models.CharField(max_length=50, verbose_name='Kategoriya (masalan, Oshxona, Yoritish)')),
                ('saving_tip', models.TextField(verbose_name="Energiyani tejash bo'yicha maslahat")),
            ],
        ),
        migrations.CreateModel(
            name='ConsumptionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appliance_name', models.CharField(max_length=100, verbose_name='Qurilma nomi')),
                ('power_watts', models.FloatField(verbose_name='Quvvati (Vatt)')),
                ('hours_per_day', models.FloatField(verbose_name='Kunlik ishlash vaqti (soat)')),
                ('daily_kwh', models.FloatField(blank=True, null=True, verbose_name='Kunlik sarf (kVt*soat)')),
                ('monthly_kwh', models.FloatField(blank=True, null=True, verbose_name='Oylik sarf (kVt*soat)')),
                ('co2_footprint', models.FloatField(blank=True, null=True, verbose_name='CO2 izi (kg)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Hisoblangan vaqt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
