# Generated by Django 6.0.5 on 2026-06-06 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumptionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appliance_name', models.CharField(max_length=100, verbose_name='Qurilma nomi')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Soni')),
                ('power_watts', models.FloatField(verbose_name='Quvvati (Vatt)')),
                ('hours_per_day', models.FloatField(verbose_name='Kunlik ishlash vaqti (soat)')),
                ('daily_kwh', models.FloatField(blank=True, null=True, verbose_name='Kunlik sarf (kVt*s)')),
                ('monthly_kwh', models.FloatField(blank=True, null=True, verbose_name='Oylik sarf (kVt*s)')),
                ('co2_footprint', models.FloatField(blank=True, null=True, verbose_name='CO2 izi (kg)')),
                ('auto_tip', models.TextField(blank=True, null=True, verbose_name='Avtomatik maslahat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Masalan: Asosiy uy, Do'kon, Sex", max_length=100)),
                ('location_type', models.CharField(choices=[('home', 'Uy'), ('business', 'Korxona')], default='home', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appliance_name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('power_watts', models.FloatField()),
                ('hours_per_day', models.FloatField()),
                ('monthly_kwh', models.FloatField(blank=True, null=True)),
                ('co2_footprint', models.FloatField(blank=True, null=True)),
                ('auto_tip', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lab.location')),
            ],
        ),
    ]
