# Generated by Django 6.0.5 on 2026-05-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appliance',
            name='saving_tip',
        ),
        migrations.AddField(
            model_name='consumptionrecord',
            name='auto_tip',
            field=models.TextField(blank=True, null=True, verbose_name='Avtomatik maslahat'),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='category',
            field=models.CharField(max_length=50, verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='daily_kwh',
            field=models.FloatField(blank=True, null=True, verbose_name='Kunlik sarf (kVt*s)'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='monthly_kwh',
            field=models.FloatField(blank=True, null=True, verbose_name='Oylik sarf (kVt*s)'),
        ),
    ]
