# Generated by Django 6.0.5 on 2026-05-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_remove_appliance_saving_tip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumptionrecord',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Soni'),
        ),
    ]
